<?php

namespace EduLazaro\Wirelist\Support;

/**
 * The package's CSS files: the core, the themes, and the bundle of both.
 */
final class Css
{
    /** The themes, in the family's order: the same as wiretables'. */
    public const THEMES = ['soft', 'glass', 'gradient', 'neon', 'minimal', 'claude', 'chatgpt', 'studio', 'synthwave', 'megaflow', 'brutalist'];

    /**
     * The core and every theme, as `wirelist.css` holds them.
     *
     * @return string
     */
    public static function bundle(): string
    {
        $dir = dirname(__DIR__, 2).'/resources/css';
        $parts = ["/* wirelist.css: GENERATED by bin/build-css.php from wirelist-core.css and themes/*.css.\n   Edit those and run `php bin/build-css.php`; for a smaller bundle import the core and one theme. */\n"];
        $parts[] = file_get_contents($dir.'/wirelist-core.css');

        foreach (self::THEMES as $theme) {
            $parts[] = file_get_contents($dir.'/themes/'.$theme.'.css');
        }

        return implode("\n", $parts);
    }
}
